name: Deploy Trip Planner to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Inject Google Maps API key into all HTML files
      - name: Inject Google Maps API Key
        run: |
          find . -name "*.html" -exec sed -i "s|__GOOGLE_MAPS_KEY__|${{ secrets.GOOGLE_MAPS_KEY }}|g" {} +
          echo "After replacement, index.html contains:"
          grep -n "GOOGLE_MAPS_KEY" index.html || true
          if grep -r "__GOOGLE_MAPS_KEY__" .; then
            echo "❌ Placeholder not replaced"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4