name: Deploy Trip Planner to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject Google Maps API Key
        run: |
          # Replace in all HTML files under frontend/
          find frontend -name "*.html" -exec sed -i "s|__GOOGLE_MAPS_KEY__|${{ secrets.GOOGLE_MAPS_KEY }}|g" {} +

          # Confirm replacement
          echo "After replacement, found in these lines:"
          grep -n "GOOGLE_MAPS_KEY" frontend/*.html

          # Fail if still placeholder
          if grep -r "__GOOGLE_MAPS_KEY__" frontend; then
            echo "❌ API key placeholder was not replaced. Check sed path or placeholder text."
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: frontend

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
